### ISSUE TITLE
Python code generation for message with an empty payload fails

### ISSUE THREAD

**Issue by pjreed** [asyncapi/python-paho-template#120]
#### Describe the bug
If a message definition has an empty payload, the python-paho-template generator fails to run and throws an exception.

#### How to Reproduce
Here is an example asyncapi.yaml file that can be used to reproduce the problem:
```yaml
asyncapi: '2.3.0'
info:
  title: Example
  version: '1.0.0'
channels:
  trigger:
    subscribe:
      summary: Does something when it receives a message.
      message:
        $ref: '#/components/messages/emptyMessage'
components:
  schemas:
    exampleHeader:
      type: object
      properties:
        HeaderValue:
          type: string
  messages:
    emptyMessage:
      summary: This message has a header but no payload.
      headers:
        $ref: '#/components/schemas/exampleHeader'
      payload:
```

Save that file as `asyncapi.yaml`, then run `ag asyncapi.yaml @asyncapi/python-paho-template -o test` on it.  You will get this exception:

```
Something went wrong:
Template render error: (example/api/node_modules/@asyncapi/python-paho-template/template/main.py) [Line 25, Column 27]
  TypeError: Cannot read property 'ext' of null
    at Object._prettifyError (example/api/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at example/api/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (example/api/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:307:3)
    at Template.render (example/api/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (example/api/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:380:17)
    at example/api/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (example/api/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (example/api/node_modules/@asyncapi/generator/lib/generator.js:703:12)
    at Generator.renderAndWriteToFile (example/api/node_modules/@asyncapi/generator/lib/generator.js:617:27)
    at Generator.generateFile (example/api/node_modules/@asyncapi/generator/lib/generator.js:667:5)
    at Generator.filesGenerationHandler (example/api/node_modules/@asyncapi/generator/lib/generator.js:542:7)
    at Walker.<anonymous> (example/api/node_modules/@asyncapi/generator/lib/generator.js:466:11)
```

#### Expected behavior
I would expect it to generate appropriate Python files.  As far as I can tell, messages with empty payloads are allowed; the `@asyncapi/html-template` generator works as expected, and [AsyncAPI Studio](https://studio.asyncapi.com/) does not indicate that it is invalid.

**Comment by anmilleriii** [comment]
I have the same error/issue.
