### ISSUE TITLE
Cannot read property 'ext' of null

### ISSUE THREAD

**Issue by ComanderKai77** [asyncapi/python-paho-template#128]
#### Describe the bug
I'm trying to generate Python code from the repo [https://bitbucket.org/qbmt/zbos-mqtt-api/src/master/](https://bitbucket.org/qbmt/zbos-mqtt-api/src/master/) .
When I'm running `ag master/zbos_mqtt-all-asyncapi.json @asyncapi/python-paho-template -o python` I'm getting the following error:

`Something went wrong:
Template render error: (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/python-paho-template/template/main.py) [Line 25, Column 27]
  TypeError: Cannot read property 'ext' of null
    at Object._prettifyError (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:305:3)
    at Template.render (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:380:17)
    at /usr/local/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (/usr/local/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:703:12)
    at Generator.renderAndWriteToFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:617:27)
    at Generator.generateFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:667:5)
    at Generator.filesGenerationHandler (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:542:7)
    at Walker.<anonymous> (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:466:11)
`

#### How to Reproduce
`git clone https://bitbucket.org/qbmt/zbos-mqtt-api/src/master/`
`ag master/zbos_mqtt-all-asyncapi.json @asyncapi/python-paho-template -o python`

#### Expected behavior
The Python code should be generated.

**Comment by dmozh** [comment]
This comment for is for drawing attention to the problem
This is actual problem, i have similiar problem
![image](https://user-images.githubusercontent.com/35331557/212065014-70a06be1-0202-4a2d-af6e-8d66e369e902.png)
