### ISSUE TITLE
Can not generate sample spec

### ISSUE THREAD

**Issue by SebastienAndreo** [asyncapi/python-paho-template#46]
#### Describe the bug

After installing as described in the documentation the `ag` tool, I was not able to generate the client code from the sample specification. 

calling the following line :
`ag /home/seb/around-api/asyncapi/python-paho-template/samples/temperature.yaml @asyncapi/python-paho-template -o ./_tempcodegen`

results in :
`Something went wrong:
Template render error: (/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/python-paho-template/template/main.py) [Line 25, Column 27]
  TypeError: key.startsWith is not a function
    at Object._prettifyError (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:307:3)
    at Template.render (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:550:10)
    at Environment.renderString (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:378:17)
    at /usr/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (/usr/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (/usr/lib/node_modules/@asyncapi/generator/lib/generator.js:680:12)
    at async Generator.renderAndWriteToFile (/usr/lib/node_modules/@asyncapi/generator/lib/generator.js:594:28)
`
The issue seems to be in `main.py` template. Proceeding with dichotomy, I was able to identify the line causing the crash: https://github.com/asyncapi/python-paho-template/blob/0d4bf163b6bc51aeff7e5a7cec5cccb66183a693/template/main.py#L28)

Unfortunately, I can not provide any solution, but removing the line makes the generation successful.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
- system with (npm 6.14.10 node v14.15.4)
- install ag 
- try to generate python template sample 

#### Expected behavior

Generation finishes successfully.

**Comment by derberg** [comment]
@SebastienAndreo hey, thanks for the issue. Could you please try running generation with `--debug` flag? This should give the answer wherein the filter error happens

**Comment by SebastienAndreo** [comment]
`
Something went wrong:
TypeError: key.startsWith is not a function
    at Channel.extension (/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/mixins/specification-extensions.js:56:14)
    at Channel.ext (/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/mixins/specification-extensions.js:75:17)
    at getFunctionNameByChannel (/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/python-paho-template/filters/all.js:297:30)
    at Context.functionName (/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/python-paho-template/filters/all.js:19:10)
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:181:38)
    at Template.render (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:550:10)
    at Environment.renderString (/usr/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:378:17)
    at /usr/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (/usr/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
`

**Comment by derberg** [comment]
@SebastienAndreo thanks a lot. Try replacing `x-scs-function-name` with `x-function-name` in the sample and lemme know if that works. If it works, would be awesome if you could submit a PR 🙏🏼

**Comment by SebastienAndreo** [comment]
Does not works, the same effect.
I debugged a little bit with the previous replacement and I found a strange place:
https://github.com/asyncapi/python-paho-template/blob/0d4bf163b6bc51aeff7e5a7cec5cccb66183a693/filters/all.js#L296

can it be that in the channel.ext method you provide an array and on the other side, you expect a string? 
Changing from `let functionName = channel.ext(['x-function-name']); ;` to `let functionName = channel.ext('x-function-name');` makes the generation successful. But I did not validate the generated python code .

**Comment by derberg** [comment]
you are right, it sould be string not array https://github.com/asyncapi/parser-js/blob/master/lib/mixins/specification-extensions.js#L74

**Comment by SebastienAndreo** [comment]
I prepare the PR

**Comment by SebastienAndreo** [comment]
I guess this issue can be closed ?

**Comment by derberg** [comment]
Was it fixed?

**Comment by SebastienAndreo** [comment]
I think yes I made the following
 PR https://github.com/asyncapi/python-paho-template/pull/47

**Comment by derberg** [comment]
ah, ok, it closed another issue, ok then, closing, thanks a lot
