### ISSUE TITLE
oneOf support

### ISSUE THREAD

**Issue by naderafshari** [asyncapi/python-paho-template#78]
###  Problem Description 

When running the python template against our yaml files we get an error which we do not see with the html template and the html results are as expected.
After narrowing down we have realized that the problem seem to be related to "oneOf"
```      
    message:
        oneOf:
        - $ref: '../events/LinkStateChangeEventV1.yaml'
        - $ref: '../events/SatTerminalEventV1.yaml' 
```
The above has the issue but when we use either one, one at a time without oneOf, it works fine 
```
      message:
        $ref: '../events/LinkStateChangeEventV1.yaml'
```
works fine and
```
      message:
        $ref: '../events/SatTerminalEventV1.yaml'
```
works fine

### This is the error
```
sh-4.4# ag _build/spec/asyncapi.yaml @asyncapi/python-paho-template  --output _build/python --force-write
Something went wrong:
Template render error: (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/python-paho-template/template/main.py) [Line 25, Column 27]
  TypeError: Cannot read property 'payload' of null
    at Object._prettifyError (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:307:3)
    at Template.render (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:380:17)
    at Promise (/usr/local/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14)
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (/usr/local/lib/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:31:10)
    at Generator.renderFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:701:12)
```
Help is appreciated and thank you in advance

**Comment by AlbertoLopSie** [comment]
Bump.

I can confirm this bug is still there.

Any development on this?
